site_name: 'Enterprise Linux 8 / CentOS 8 In Action'
site_description: 'ExteptionALLy OPEN labs for Enterprise Linux 8 / CentOS 8 In Action training course'
site_author: 'All Open Patryk Malina'
site_url: 'https://el8-lab.all-open.com'
repo_url: 'https://github.com/All-Open/el8-lab'
nav:
  - Start:
      - Welcome!: 'index.md'
  - Lab Setup:
      - Getting Started: 'setup/getting-started.md'
      - Lab System Setup:
        - VM Installation: 'setup/vm.md'
        - Vagrant: 'setup/vagrant.md'
        - Public Cloud: 'setup/cloud.md'
      - System Registration: 'setup/registration.md'
      - Installing Lab RPM: 'setup/rpm.md'
  - Labs:
      - Intro: 'labs/intro.md'
      - Prequisites: 'labs/prereq.md'
      - Package Management: 'labs/packages.md'
      - DNF: 'labs/dnf.md'
      - Using Modules: 'labs/modules.md'
      - Switching Modules: 'labs/switching-modules.md'
      - There is More: 'labs/outro.md'
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'deep orange'
  feature:
    tabs: true
  custom_dir: 'custom_theme/'
  logo: 'img/all-open-logo.png'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.smartsymbols
  - toc:
      permalink: true
extra:
  social:
    - type: 'github'
      link: 'https://github.com/All-Open'
    - type: 'twitter'
      link: 'https://twitter.com/BeAllOpen'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/all-open'
    - type: 'facebook'
      link: 'https://www.facebook.com/AllOpenIT'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/cookie.js'
google_analytics: ['UA-149838316-1', 'el8-lab.all-open.com']
